### ISSUE TITLE
Error when trying to get profile

### ISSUE THREAD

**Issue by bizkit1** [iammuho/Phalcon-Facebook-Library#3]
Hi there and nice work. I have some trouble implementing fb login. I login with my fb account, but when o try to get profile information like this   <?php print_r($this->facebook->fbLogin());?> i get Fatal error: Uncaught OAuthException: An active access token must be used to query information about the current user. thrown in D:\apache\htdocs\live.romanticfm.ro\invo\app\library\Mars\Social\sdk\base_facebook.php on line 1271. Any ideea why?

**Comment by iammuho** [comment]
Can you check the server time ?
